-- MySQL Script generated by MySQL Workbench
-- Sat May  8 13:41:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cursoDaMinhaVida` DEFAULT CHARACTER SET utf8 ;
USE `db_cursoDaMinhaVida` ;

-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `Informática` TINYINT NOT NULL,
  `Ilustração` TINYINT NOT NULL,
  `Culinaria` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(95) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_curso`, `id_categoria`),
  CONSTRAINT `fk_tb_curso_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_cursoDaMinhaVida`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO tb_categoria(Informática, Ilustração, Culinaria) VALUES (true, false, false), (false, true, false), (false, false, true);
SELECT * FROM tb_categoria;

INSERT INTO tb_curso(nome, valor, id_categoria) VALUES ("Quanta Academia", 349.00, 2), ("Culinária Japonesa", 120.99, 3), ("Generation", 0, 1);
SELECT * FROM tb_curso;

SELECT * FROM tb_curso WHERE `valor` > 50;
SELECT * FROM tb_curso WHERE `valor` BETWEEN 3 AND 60;
SELECT * FROM tb_curso WHERE `nome` LIKE "C%";

SELECT * FROM tb_curso INNER JOIN tb_categoria on tb_curso.id_categoria = tb_categoria.id_categoria;
SELECT * FROM tb_curso INNER JOIN tb_categoria on tb_curso.id_categoria = tb_categoria.id_categoria WHERE `tb_curso`.`id_categoria`= 3;