-- MySQL Script generated by MySQL Workbench
-- Sat May  8 12:46:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_construindo_a_nossa_vida` DEFAULT CHARACTER SET utf8 ;
USE `db_construindo_a_nossa_vida` ;

-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `ferramentas` TINYINT NOT NULL,
  `material` TINYINT NOT NULL,
  `tintura` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_categoria`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_construindo_a_nossa_vida`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO tb_categoria(ferramentas, material, tintura) VALUES (true, false, false), (false, true, false), (false, false, true);
SELECT * FROM tb_categoria;

INSERT INTO tb_produto(nome, valor, id_categoria) VALUES ("Coral Amêndoa", 34.99, 3), ("Alicate", 15.99, 1), ("Massa Corrida", 41.99, 2);
SELECT * FROM tb_produto;

SELECT * FROM tb_produto WHERE `valor` > 50;
SELECT * FROM tb_produto WHERE `valor` BETWEEN 3 AND 60;
SELECT * FROM tb_produto WHERE `nome` LIKE "C%";

SELECT * FROM tb_produto INNER JOIN tb_categoria on tb_produto.id_categoria = tb_categoria.id_categoria;
SELECT * FROM tb_produto INNER JOIN tb_categoria on tb_produto.id_categoria = tb_categoria.id_categoria WHERE `tb_produto`.`id_categoria`= 3;