-- MySQL Script generated by MySQL Workbench
-- Thu May  6 19:56:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_das_carnes` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_das_carnes` ;

-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `bovina` TINYINT NOT NULL,
  `suína` TINYINT NOT NULL,
  `aves` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `peso` DECIMAL(5,2) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_categoria`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_cidade_das_carnes`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO tb_categoria(bovina, suína, aves) VALUES (true, false, false), (false, true, false), (false, false, true);
SELECT * FROM tb_categoria;

INSERT INTO tb_produto(nome, valor, peso, id_categoria) VALUES ("Salsicha Sadia", 20.99, 1.02, 2), ("Carne Moída", 19.99, 1.0, 1), ("Frango a Passarinho", 40.5, 3.2, 3);
SELECT * FROM tb_produto;

SELECT * FROM tb_produto WHERE `valor` > 50;
SELECT * FROM tb_produto WHERE `valor` BETWEEN 3 AND 60;
SELECT * FROM tb_produto WHERE `nome` LIKE "C%";

SELECT * FROM tb_produto INNER JOIN tb_categoria on tb_categoria.id_categoria = tb_produto.id_categoria;
SELECT * FROM tb_produto INNER JOIN tb_categoria on tb_categoria.id_categoria = tb_produto.id_categoria WHERE `tb_produto`.`id_categoria`= 3;